### ISSUE TITLE
Support local file path or array buffer

### ISSUE THREAD

**Issue by OJFord** [gtm-nayan/svelte-pdfjs#5]
Currently the PDF must be accessible by URL, but for more flexibility and supporting different use cases it'd be nice to be able to provide a local file path or the contents directly.

Specifically in my case, I'm looking for something to use with Tauri; so I can either provide the data directly from a non-HTTP API call, or first write it to a temporary file, but I can't really conveniently make it available at a URL.

**Comment by gtm-nayan** [comment]
@OJFord The file prop is optional so you should be able to pass in the contents through `data` on the `loadOptions` prop.
See [DocumentInitParameters.data](https://github.com/mozilla/pdf.js/blob/41dab8e7b6c1e2684d4afabb8f02e40a874d8e85/src/display/api.js#L131)

**Comment by OJFord** [comment]
Ah yes, thanks!
