### ISSUE TITLE
Expose PDFDocumentProxy, or some other way of accessing document info

### ISSUE THREAD

**Issue by OJFord** [gtm-nayan/svelte-pdfjs#6]
For example, as far as I can see it isn't possible to limit the supplied `pageNumber` to the actual total number of pages, or to display `page {pageNumber} of {pageTotal}` - since there's no way of getting the total?

[`PDFDocumentProxy`](https://github.com/mozilla/pdfjs-dist/blob/bd2a6cd87f9e0c3a9b3197d5d27acfb99886629b/types/src/display/api.d.ts#L724) has a `numPages` method that could provide this, along with other potentially useful metadata.

**Comment by gtm-nayan** [comment]
v0.1.1: `Document` now emits `loadsuccess` with a detail of type `PDFDocumentProxy` and `loaderror` with a detail of type `Error`.

The events currently don't have typing for inline event handlers so I'll keep this open until I can figure that out.
